# Generated by Django 4.0.6 on 2022-08-06 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id_producto')),
                ('nombre_producto', models.CharField(default=None, max_length=50, unique=True, verbose_name='nombre_producto')),
                ('presentacion', models.CharField(default=None, max_length=500, verbose_name='presentacion')),
                ('precio', models.FloatField(default=0.0, verbose_name='precio')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id_producto')),
                ('cantidad', models.IntegerField(default=0, verbose_name='cantidad')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.producto')),
            ],
        ),
    ]
