# Generated by Django 4.0.6 on 2022-08-06 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.producto', unique=True),
        ),
    ]
