# Generated by Django 4.0.6 on 2022-08-06 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0004_alter_articulo_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='id_producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab_app.producto'),
        ),
    ]
