# Generated by Django 4.0.6 on 2022-07-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id_usuario')),
                ('username', models.CharField(default='loser', max_length=30, unique=True, verbose_name='usuario')),
                ('password', models.CharField(max_length=300, verbose_name='password')),
                ('apellido', models.CharField(default='apellido', max_length=30, verbose_name='apellido')),
                ('nombre', models.CharField(default='nombre', max_length=30, verbose_name='nombre')),
                ('email', models.EmailField(default='nombre@dominio.com', max_length=100, verbose_name='correo')),
                ('direccion', models.CharField(default='calle 1 carrera 1 # 1', max_length=50, verbose_name='direccion')),
                ('telefono', models.CharField(default='00000000', max_length=15, verbose_name='telefono')),
                ('estado', models.BooleanField(default=True, verbose_name='activo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
