# Generated by Django 4.0.6 on 2022-07-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id_producto')),
                ('nombre_producto', models.CharField(default=None, max_length=50, unique=True, verbose_name='nombre_producto')),
                ('presentacion', models.CharField(default=None, max_length=500, verbose_name='presentacion')),
                ('precio', models.FloatField(default=0.0, verbose_name='precio')),
            ],
        ),
    ]
