# Generated by Django 4.0.6 on 2022-07-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(default='apellido', max_length=30, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_usuario',
            field=models.EmailField(default='aaaa@ddd.com', max_length=100, primary_key=True, serialize=False, verbose_name='ID_Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='nombre', max_length=30, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(default='00000000', max_length=15, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=300, verbose_name='password'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
