# Generated by Django 4.0.6 on 2022-07-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_app', '0002_remove_user_email_remove_user_id_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(default='calle 1 carrera 1 # 1', max_length=50, verbose_name='Telefono'),
        ),
    ]
