# Generated by Django 4.0.6 on 2022-07-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_app', '0003_user_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellido',
            field=models.CharField(default='apellido', max_length=30, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(default='calle 1 carrera 1 # 1', max_length=50, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_usuario',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, verbose_name='id_usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='nombre', max_length=30, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(default='00000000', max_length=15, verbose_name='telefono'),
        ),
    ]
