# Generated by Django 4.0.6 on 2022-07-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_app', '0004_alter_user_apellido_alter_user_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='nombre@dominio.com', max_length=100, verbose_name='correo'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='loser', max_length=30, unique=True, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_usuario',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id_usuario'),
        ),
    ]
